apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quote-app
  template:
    metadata:
      labels:
        app: quote-app
    spec:
      containers:
      - name: quote-app
        image: tanujsaini123/quote-app:latest
        ports:
        - containerPort: 5000
