apiVersion: v1
kind: Service
metadata:
  name: quote-service
spec:
  type: NodePort
  selector:
    app: quote-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
